### ISSUE TITLE
Error: 403

### ISSUE THREAD

**Issue by pdelteil** [mateofumis/dumpdork#1]
I followed the steps of installation but I got this output:

```
Error: 403
No results found or an error occurred.
Traceback (most recent call last):
  File "/home/user/.local/bin/dumpdork", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/dumpdork/main.py", line 132, in main
    json.dump(response.json(), json_file, ensure_ascii=False, indent=4)
AttributeError: 'NoneType' object has no attribute 'json'
```

The issue was that I was not subscribed to the API (clicking option `Subscribe to Test`)

**Comment by mateofumis** [comment]
Hi @pdelteil ,

Indeed, as you said, if you were not subscribed to the API, it will return a 403 status code because the API requires authentication using the TOKEN. This token can be obtained by registering for free and then claiming it.

**I would like to ask you if you have tried the following steps:**

1. Visit [https://rapidapi.com/auth/login/

**Comment by mateofumis** [comment]
Hi @pdelteil ,

Indeed, as you said, if you were not subscribed to the API key, the script will return you a **403** status code because the API requires an authorization using the **API key**.

**I'd would like to ask you if you followed these steps:**

1. Visit [https://rapidapi.com/auth/login/](https://rapidapi.com/auth/login/) and Sign up (or Log In).
2. Visit [https://rapidapi.com/herosAPI/api/google-search74/playground](https://rapidapi.com/herosAPI/api/google-search74/playground) and:
    1. Click on `Subscribe to Test`
    2. Copy your API key and save it to then put it in your `config.yaml`.
    3. Click on `Start Free Plan`
    4. Click on `Subscribe`
    5. Done! ;)

I leave you these screenshots to make it easier to explain the steps:

![1_claim-api-key](https://github.com/user-attachments/assets/a5d1a7fd-32c1-4b04-a8ef-8bf993435c49)
![2_start-free-plan](https://github.com/user-attachments/assets/f5a9433d-71f7-40f1-be2e-cb6cca0d7841)
![3_final-step-subscribe](https://github.com/user-attachments/assets/48edde9e-7764-411c-9a43-279798f0d691)

---

6. Additionally, *DumpDork has the feature `--wizard`*. So, just by run `dumpdork --wizard` 

```bash
❯ dumpdork --wizard
Welcome to the API Key Setup Wizard!
1. Signup at: https://rapidapi.com/herosAPI/api/google-search74/playground
2. Subscribe for free and copy the API key.
Enter your RapidAPI key:
```

With this, the setup is easier instead of configure manually the file `~/.config/dumpdork/config.yaml` (or wherever you save your `config.yaml` using the argument `dumpdork --config-file /path/to/config.yaml`. Default directory is: `~/.config/dumpdork/`

**Comment by pdelteil** [comment]
Thank you for your quick response. 

The only step I missed was subscribing, I didn't see that step on the main page's installation steps.
